security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:8282/oauth/authorize
      access-token-uri: http://authserver:8282/oauth/token
    resource:
      token-info-uri: http://authserver:8282/oauth/check_token
server:
  port: 8082
  servlet:
    session:
      cookie:
        name: DSESSIONID


